"""initial schema

Revision ID: b4efcae13e7b
Revises: 
Create Date: 2026-08-24 12:13:18.234346

"""
from __future__ import annotations

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision = 'b4efcae13e7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('masked_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('masked_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upi_vpa_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consent_flags', sa.JSON(), nullable=True),
    sa.Column('locale_pref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardrailpolicy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_retries_per_case', sa.Integer(), nullable=False),
    sa.Column('retry_cooldown_hours', sa.Integer(), nullable=False),
    sa.Column('message_cap_per_case', sa.Integer(), nullable=False),
    sa.Column('message_cap_window_days', sa.Integer(), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=False),
    sa.Column('quiet_hours_end', sa.Time(), nullable=False),
    sa.Column('allowed_channels', sa.JSON(), nullable=True),
    sa.Column('consent_required_channels', sa.JSON(), nullable=True),
    sa.Column('amount_immutability', sa.Boolean(), nullable=False),
    sa.Column('case_ttl_days', sa.Integer(), nullable=False),
    sa.Column('payment_link_expiry_hours', sa.Integer(), nullable=False),
    sa.Column('payment_link_single_use', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulationrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('cases_requested', sa.Integer(), nullable=False),
    sa.Column('cases_created', sa.Integer(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('PAYMENT_FAILED', 'CHECKOUT_ABANDONED', 'SUBSCRIPTION_CHARGE_FAILED', 'PAYMENT_CAPTURED', name='eventtype'), nullable=False),
    sa.Column('razorpay_payload_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('ground_truth_recoverable', sa.Boolean(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_event_id', name='uq_event_source_id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_source_event_id'), ['source_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('merchant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('razorpay_key_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guardrail_policy_id', sa.Integer(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guardrail_policy_id'], ['guardrailpolicy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('flow_type', sa.Enum('PAYMENT_FAILURE', 'CHECKOUT_ABANDONMENT', 'SUBSCRIPTION_MANDATE', name='flowtype'), nullable=False),
    sa.Column('state', sa.Enum('NEW', 'PROCESSING', 'AWAITING_OUTCOME', 'RECOVERED', 'LOST', 'ESCALATED_TO_HUMAN', 'STOPPED_UNRECOVERABLE', name='casestate'), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('messages_sent_count', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('policy_snapshot', sa.JSON(), nullable=True),
    sa.Column('related_case_ids', sa.JSON(), nullable=True),
    sa.Column('terminal_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_action_at', sa.DateTime(), nullable=True),
    sa.Column('case_deadline_at', sa.DateTime(), nullable=True),
    sa.Column('deferred_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_ref')
    )
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('auditlogentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.Enum('AGENT', 'SYSTEM', 'HUMAN', name='actor'), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('before_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('after_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name='uq_auditlog_id')
    )
    with op.batch_alter_table('auditlogentry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditlogentry_case_id'), ['case_id'], unique=False)

    op.create_table('decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('proposed_action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_params', sa.JSON(), nullable=True),
    sa.Column('message_language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message_tone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reasoning', sqlmodel.sql.sqltypes.AutoString(length=280), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'APPROVED', 'EXECUTED', 'BLOCKED', name='decisionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_case_id'), ['case_id'], unique=False)

    op.create_table('diagnosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('root_cause_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reasoning', sqlmodel.sql.sqltypes.AutoString(length=280), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosis_case_id'), ['case_id'], unique=False)

    op.create_table('outcome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('outcome_type', sa.Enum('RECOVERED', 'LOST', 'STOPPED', 'ESCALATED', name='outcometype'), nullable=False),
    sa.Column('amount_recovered', sa.Integer(), nullable=False),
    sa.Column('recovered_at', sa.DateTime(), nullable=True),
    sa.Column('matched_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outcome', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outcome_case_id'), ['case_id'], unique=False)

    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor', sa.Enum('AGENT', 'SYSTEM', 'HUMAN', name='actor'), nullable=False),
    sa.Column('external_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message_body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_case_id'), ['case_id'], unique=False)

    op.create_table('guardrailcheck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('violated_rules', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guardrailcheck', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guardrailcheck_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guardrailcheck_decision_id'), ['decision_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardrailcheck', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guardrailcheck_decision_id'))
        batch_op.drop_index(batch_op.f('ix_guardrailcheck_case_id'))

    op.drop_table('guardrailcheck')
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_case_id'))

    op.drop_table('action')
    with op.batch_alter_table('outcome', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outcome_case_id'))

    op.drop_table('outcome')
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosis_case_id'))

    op.drop_table('diagnosis')
    with op.batch_alter_table('decision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_case_id'))

    op.drop_table('decision')
    with op.batch_alter_table('auditlogentry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditlogentry_case_id'))

    op.drop_table('auditlogentry')
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_case_order_id'))

    op.drop_table('case')
    op.drop_table('merchant')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_event_source_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_order_id'))

    op.drop_table('event')
    op.drop_table('simulationrun')
    op.drop_table('guardrailpolicy')
    op.drop_table('customer')
    # ### end Alembic commands ###
